import 'dotenv/config';
import { CharacterMoveModel } from '../models/CharacterMove';
import { createClient, Client } from '@libsql/client';

// キャラクター技データのシード
// ソースのフレーム表および各キャラクター解説に基づく全キャラクターの技データ

const characterMovesData: Record<string, Array<{ moveName: string; moveNotation: string; moveNameEn?: string }>> = {
  'ソル=バッドガイ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6S', moveNotation: '6S' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ガンフレイム', moveNotation: '236P', moveNameEn: 'Gun Flame' },
    { moveName: 'ヴォルカニックヴァイパー', moveNotation: '623S', moveNameEn: 'Volcanic Viper' },
    { moveName: 'バンディットリヴォルバー', moveNotation: '236K', moveNameEn: 'Bandit Revolver' },
    { moveName: 'バンディットブリンガー', moveNotation: '214K', moveNameEn: 'Bandit Bringer' },
    { moveName: 'ぶっきらぼうに投げる', moveNotation: '623K', moveNameEn: 'Brash Throw' },
    { moveName: 'ナイトレイドヴォルテックス', moveNotation: '214S', moveNameEn: 'Night Raid Vortex' },
    { moveName: 'ファフニール', moveNotation: '41236H', moveNameEn: 'Fafnir' },
    { moveName: 'タイランレイヴ', moveNotation: '632146H', moveNameEn: 'Tyrant Rave' },
    { moveName: 'ヘヴィモブセメタリー', moveNotation: '214214H', moveNameEn: 'Heavy Mob Cemetery' }
  ],
  'カイ=キスク': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'スタンエッジ', moveNotation: '236S', moveNameEn: 'Stun Edge' },
    { moveName: 'チャージスタンエッジ', moveNotation: '236H', moveNameEn: 'Charged Stun Edge' },
    { moveName: 'ヴェイパースラスト', moveNotation: '623S', moveNameEn: 'Vapor Thrust' },
    { moveName: 'スタンディッパー', moveNotation: '236K', moveNameEn: 'Stun Dipper' },
    { moveName: 'フードゥルアルク', moveNotation: '214K', moveNameEn: 'Foudre Arc' },
    { moveName: 'ダイアエクラ', moveNotation: '214S', moveNameEn: 'Dire Eclat' },
    { moveName: 'ライド・ザ・ライトニング', moveNotation: '632146H', moveNameEn: 'Ride the Lightning' },
    { moveName: 'セイクリッドエッジ', moveNotation: '236236P', moveNameEn: 'Sacred Edge' },
    { moveName: 'ドラゴンインストール', moveNotation: '214214H', moveNameEn: 'Dragon Install' }
  ],
  'メイ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'イルカさん・横', moveNotation: '6S' },
    { moveName: 'イルカさん・縦', moveNotation: '8S' },
    { moveName: 'オーバーヘッドキッス', moveNotation: '623K' },
    { moveName: '有栖川スパークル', moveNotation: '214P' },
    { moveName: 'グレート山田アタック', moveNotation: '236236S' },
    { moveName: '五所川原', moveNotation: '632146H' }
  ],
  'アクセル・ロウ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '鎌閃撃', moveNotation: '6S' },
    { moveName: '冬蟷螂', moveNotation: '41236H' },
    { moveName: '潦', moveNotation: '623S' },
    { moveName: '蝸牛', moveNotation: '214H' },
    { moveName: '百重鎌焼', moveNotation: '632146H' },
    { moveName: 'ワンヴィジョン', moveNotation: '236236S' }
  ],
  'チップ・ザナフ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'αブレード', moveNotation: '236P' },
    { moveName: 'βブレード', moveNotation: '623S' },
    { moveName: 'γブレード', moveNotation: '236H' },
    { moveName: '冽掌', moveNotation: '236S' },
    { moveName: '幻朧斬', moveNotation: '632146S' },
    { moveName: '万鬼滅砕', moveNotation: '236236P' },
    { moveName: '斬星狼牙', moveNotation: '236236H' }
  ],
  'ポチョムキン': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ハンマフォール', moveNotation: '6H' },
    { moveName: 'ポチョムキンバスター', moveNotation: '632146P' },
    { moveName: 'ヒートナックル', moveNotation: '623H' },
    { moveName: 'メガフィスト', moveNotation: '236P' },
    { moveName: 'スライドヘッド', moveNotation: '236S' },
    { moveName: 'F.D.B.', moveNotation: '214S' },
    { moveName: 'ガルダインパクト', moveNotation: '214H' },
    { moveName: 'ヒートタックル', moveNotation: '41236H' },
    { moveName: 'ヘブンリーポチョムキンバスター', moveNotation: '236236S' },
    { moveName: 'ガイガンター改', moveNotation: '632146H' }
  ],
  'ファウスト': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '突きます', moveNotation: '236S' },
    { moveName: '何が出るかな？', moveNotation: '236P' },
    { moveName: '涅和混練', moveNotation: '236K' },
    { moveName: 'メッタ刈り', moveNotation: '632146S' },
    { moveName: '愛', moveNotation: 'j.236P' },
    { moveName: '久延毘古', moveNotation: '214P' },
    { moveName: 'エキサイティング骨折', moveNotation: '236236H' }
  ],
  'ミリア=レイジ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'タンデムトップ', moveNotation: '236S' },
    { moveName: 'ラストシェイカー', moveNotation: '214P' },
    { moveName: 'アイアンセイバー', moveNotation: '214K' },
    { moveName: 'バッドムーン', moveNotation: 'j.236P' },
    { moveName: 'ミラーシュ', moveNotation: '214S' },
    { moveName: 'カピエル', moveNotation: '214H' },
    { moveName: 'セプテムヴォイシズ', moveNotation: '236236P' },
    { moveName: 'ウィンガー', moveNotation: '632146H' }
  ],
  'ザトー=ONE': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'インヴァイトヘル', moveNotation: '22S' },
    { moveName: '「突く」', moveNotation: 'P離し' },
    { moveName: '「多い！」', moveNotation: 'S離し' },
    { moveName: '「跳ねる」', moveNotation: 'K離し' },
    { moveName: '「張り合う」', moveNotation: 'H離し' },
    { moveName: 'ダムドファング', moveNotation: '623S' },
    { moveName: 'ブレイク・ザ・ロウ', moveNotation: '214K' },
    { moveName: 'ドランカーシェイド', moveNotation: '214S' },
    { moveName: 'アモルファス', moveNotation: '632146H' },
    { moveName: 'サンヴォイド', moveNotation: '236236S' }
  ],
  'ラムレザル=ヴァレンタイン': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'バヨネート', moveNotation: '236S' },
    { moveName: 'ダウロ', moveNotation: '623P' },
    { moveName: 'シルドデトルオ', moveNotation: '214K' },
    { moveName: 'サブロバート', moveNotation: '214H' },
    { moveName: 'エラルルーモ', moveNotation: '214P' },
    { moveName: 'オンド', moveNotation: '214S' },
    { moveName: 'カルヴァドス', moveNotation: '632146H' },
    { moveName: 'モルトバート', moveNotation: '236236S' }
  ],
  'レオ=ホワイトファング': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'グラヴィエットヴァーダ', moveNotation: '6S' },
    { moveName: 'アイゼンシュトルム', moveNotation: '8S' },
    { moveName: 'エアースト・カルタスゲシュトゥーバー', moveNotation: '236S' },
    { moveName: 'ツヴァイト・カルタスゲシュトゥーバー', moveNotation: '236H' },
    { moveName: 'トゥルブレンツ', moveNotation: '214S' },
    { moveName: 'シュタイルヴァービル', moveNotation: '236236H' },
    { moveName: 'ライデンシャフトディリガント', moveNotation: '632146H' }
  ],
  '名残雪': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '粒雪', moveNotation: '236S' },
    { moveName: '不香', moveNotation: '236K' },
    { moveName: '冠雪', moveNotation: '623H' },
    { moveName: '垂雪', moveNotation: '623S' },
    { moveName: 'Bloodsucking Universe', moveNotation: '623P' },
    { moveName: '忘れ雪', moveNotation: '632146H' },
    { moveName: '残雪', moveNotation: '214214H' }
  ],
  'ジオヴァーナ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'トロヴァォン', moveNotation: '236H' },
    { moveName: 'セパルトゥラ', moveNotation: '214K' },
    { moveName: 'ソウ・ナセンテ', moveNotation: '623S' },
    { moveName: 'ソウ・ポエンチ', moveNotation: '214S' },
    { moveName: 'ヴェンターニア', moveNotation: '632146H' },
    { moveName: 'テンペスターヂ', moveNotation: 'j.236236H' }
  ],
  '闇慈': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '疾', moveNotation: '236P' },
    { moveName: '紅', moveNotation: '623H' },
    { moveName: '風神', moveNotation: '236S' },
    { moveName: '一誠奥義「彩」', moveNotation: '632146H' },
    { moveName: '花鳥風月・改', moveNotation: '236236S' }
  ],
  'イノ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '大木をさする手', moveNotation: '236S' },
    { moveName: '狂言実行', moveNotation: 'j.214P' },
    { moveName: '抗鬱音階', moveNotation: '214P' },
    { moveName: 'ケミカル愛情', moveNotation: '214K' },
    { moveName: '狂愛アジタート', moveNotation: '236K' },
    { moveName: 'メガロマニア', moveNotation: '632146H' },
    { moveName: '限界フォルテッシモ', moveNotation: 'j.236236S' }
  ],
  'ゴールドルイス': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ベヒモスタイフーン', moveNotation: '半回転+H' },
    { moveName: 'サンダーバード', moveNotation: '214P' },
    { moveName: 'スカイフィッシュ', moveNotation: '214S' },
    { moveName: 'ダウン・ウィズ・ザ・システム', moveNotation: '632146P' },
    { moveName: 'バーン・イット・ダウン', moveNotation: '236236S' }
  ],
  'ジャック・オー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'サーヴァント召喚', moveNotation: '214P' },
    { moveName: '攻撃指示', moveNotation: '236P' },
    { moveName: '防御指示', moveNotation: '236K' },
    { moveName: 'カウントダウン', moveNotation: '236S' },
    { moveName: 'サーヴァントシュート', moveNotation: '236H' },
    { moveName: 'フォーエヴァーエリシオンドライバー', moveNotation: '632146H' }
  ],
  'ハッピーケイオス': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '銃を構える', moveNotation: '214S' },
    { moveName: 'しっかり狙いを定める', moveNotation: '236S' },
    { moveName: 'リロード', moveNotation: '22P' },
    { moveName: 'フォーカス', moveNotation: '214P' },
    { moveName: '前転', moveNotation: '236K' },
    { moveName: 'スケープゴート', moveNotation: '214K' },
    { moveName: 'カース', moveNotation: '236P' },
    { moveName: 'デウス・エクス・マキナ', moveNotation: '632146H' }
  ],
  '梅喧': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '畳返し', moveNotation: '236S' },
    { moveName: '蚊鉤', moveNotation: '41236S' },
    { moveName: '妖斬扇', moveNotation: 'j.236S' },
    { moveName: '柊', moveNotation: '623P' },
    { moveName: '連ね三途渡し', moveNotation: '632146H' },
    { moveName: '拳銃', moveNotation: '236236S' }
  ],
  'テスタメント': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'グレイブリーパー', moveNotation: '236S' },
    { moveName: 'アンホーリーダイバー', moveNotation: '214P' },
    { moveName: 'ポゼッション', moveNotation: '214S' },
    { moveName: 'アービターサイン', moveNotation: '214H' },
    { moveName: 'ノストロヴィア', moveNotation: '236236P' },
    { moveName: 'カラミティ・ワン', moveNotation: '632146H' }
  ],
  'ブリジット': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ストップ＆ダッシュ', moveNotation: '236S' },
    { moveName: 'ローリング移動', moveNotation: '214K' },
    { moveName: 'スターシップ', moveNotation: '623S' },
    { moveName: 'キックスタートマイハート', moveNotation: '236K' },
    { moveName: 'ロジャーダイブ', moveNotation: 'j.214K' },
    { moveName: 'ロック ザ ベイビー', moveNotation: '632146K' },
    { moveName: 'ループ ザ ループ', moveNotation: '632146H' },
    { moveName: '帰ってきたキルマシーン', moveNotation: '236236S' }
  ],
  'シン=キスク': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ビークドライバー', moveNotation: '236H' },
    { moveName: 'ホークベイカー', moveNotation: '623S' },
    { moveName: 'フーフスタンプ', moveNotation: '214S' },
    { moveName: 'エルクハント', moveNotation: '214K' },
    { moveName: 'R.T.L', moveNotation: '632146H' },
    { moveName: 'タイランバレル', moveNotation: '236236P' }
  ],
  'ベッドマン?': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '4BA', moveNotation: '236S' },
    { moveName: '4B3', moveNotation: '236K' },
    { moveName: '4B9', moveNotation: '214H' },
    { moveName: '0x$0.20', moveNotation: '214P' },
    { moveName: '0x$1.00', moveNotation: '214K' },
    { moveName: '13C', moveNotation: '236236S' },
    { moveName: '4CC', moveNotation: '632146H' }
  ],
  'アスカ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '詠唱', moveNotation: '236P' },
    { moveName: 'ブックマーク', moveNotation: '22P' },
    { moveName: 'マナ回復', moveNotation: '214P' },
    { moveName: 'テストケース変更', moveNotation: '214K' },
    { moveName: 'サブミクロン粒子高圧縮球', moveNotation: '632146H' }
  ],
  'ジョニー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ミストファイナー', moveNotation: '236P' },
    { moveName: 'ディール', moveNotation: '214P' },
    { moveName: '跳躍', moveNotation: '623K' },
    { moveName: '燕穿牙', moveNotation: 'j.214S' },
    { moveName: 'それが俺の名だ', moveNotation: '632146H' },
    { moveName: 'ジョーカートリック', moveNotation: '236236S' }
  ],
  'エルフェルト': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'Missシャルロット', moveNotation: '236S' },
    { moveName: 'ボンボン・ショコラ', moveNotation: '214S' },
    { moveName: 'やります！', moveNotation: '214K' },
    { moveName: '決めます！', moveNotation: '236P' },
    { moveName: 'ジュガント ダ パルフェーオ', moveNotation: '236236S' },
    { moveName: 'ボンボニエール', moveNotation: '632146H' }
  ],
  'A.B.A': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '結合と変性', moveNotation: '236P' },
    { moveName: '変転と感化', moveNotation: '214P' },
    { moveName: '牽引と随順', moveNotation: '236K' },
    { moveName: '戮力と傾動', moveNotation: '214K' },
    { moveName: '威喝と嗚咽', moveNotation: '236S' },
    { moveName: '抑圧と束縛', moveNotation: '236H' },
    { moveName: '逆上と驚愕', moveNotation: '214S' },
    { moveName: '断罪と情動', moveNotation: '214H' },
    { moveName: '鍵の支配者', moveNotation: '632146H' },
    { moveName: '鍵の守護者', moveNotation: '236236S' }
  ],
  'スレイヤー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'マッパハンチ', moveNotation: '236P' },
    { moveName: 'ダンディーステップ', moveNotation: '214P' },
    { moveName: '血を吸う宇宙', moveNotation: '623K' },
    { moveName: 'ハンドオブドゥーム', moveNotation: '214H' },
    { moveName: 'スーパーマッパハンチ', moveNotation: '632146H' },
    { moveName: 'ラスト・ホライズン', moveNotation: '236236P' }
  ],
  'ディズィー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '魚を捕る時に使ってたんです', moveNotation: '236S' },
    { moveName: '氷原', moveNotation: '214K' },
    { moveName: '焼き栗が欲しい時に使ってたんです', moveNotation: '214S' },
    { moveName: 'よく話し相手になってくれました', moveNotation: '214P' },
    { moveName: 'ミカエルソード', moveNotation: '623S' },
    { moveName: '光の翼', moveNotation: '214214P' },
    { moveName: 'インペリアルレイ', moveNotation: '632146S' },
    { moveName: 'ガンマレイ', moveNotation: '236236H' }
  ],
  'ヴェノム': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ボール', moveNotation: '236P' },
    { moveName: 'ボール生成', moveNotation: '22P' },
    { moveName: 'ＱＶ', moveNotation: '623P' },
    { moveName: 'スティンガー', moveNotation: '41236S' },
    { moveName: 'カーカス', moveNotation: '8S' },
    { moveName: 'トリアンバカ', moveNotation: '632146P' },
    { moveName: 'ダークエンジェル', moveNotation: '236236S' },
    { moveName: 'ナヴァラートナ', moveNotation: '214214H' }
  ],
  'ユニカ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ストリーク', moveNotation: '236S' },
    { moveName: 'ペネ', moveNotation: '236K' },
    { moveName: 'トップ', moveNotation: '214K' },
    { moveName: 'ブラスト', moveNotation: '623S' },
    { moveName: 'ブレイズ', moveNotation: '214H' },
    { moveName: 'ブリッツ', moveNotation: '236P' },
    { moveName: 'メガデス', moveNotation: '236236S' },
    { moveName: 'ウェポンズフリー', moveNotation: '632146H' }
  ],
  'ルーシー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'モノワイヤー', moveNotation: '236S' },
    { moveName: 'ユニティ', moveNotation: '214S' },
    { moveName: 'スプリントアタック', moveNotation: '236K' },
    { moveName: 'モノワイヤー・ブレイクアウト', moveNotation: '623S' },
    { moveName: 'ライブワイヤー', moveNotation: '632146H' },
    { moveName: 'クイックハック', moveNotation: '214214P' }
  ]
};

async function seedCharacterMoves() {
  for (const [characterName, moves] of Object.entries(characterMovesData)) {
    console.log(`Seeding moves for ${characterName}...`);

    for (const move of moves) {
      try {
        await CharacterMoveModel.create(
          characterName,
          move.moveName,
          move.moveNotation,
          null, // moveType
          move.moveNameEn || null // moveNameEn
        );
      } catch (error: any) {
        // UNIQUE制約エラー（すでに登録済み）は無視
        if (error.message && error.message.includes('UNIQUE constraint failed')) {
          console.log(`  Skipped (already exists): ${move.moveName}`);
        } else {
          throw error;
        }
      }
    }

    console.log(`  ✓ Completed ${characterName} (${moves.length} moves)`);
  }
}

// スクリプトとして直接実行された場合
if (require.main === module) {
  const url = process.env.TURSO_DATABASE_URL;
  const authToken = process.env.TURSO_AUTH_TOKEN;

  if (!url || !authToken) {
    console.error('TURSO_DATABASE_URL and TURSO_AUTH_TOKEN must be set');
    process.exit(1);
  }

  // データベース接続を作成
  const db: Client = createClient({ url, authToken });
  console.log('Connected to database');

  // database/index.ts のdbをセット
  const { setDatabase } = require('./index.ts');
  setDatabase(db);

  seedCharacterMoves()
    .then(() => {
      console.log('Seed completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seed failed:', error);
      process.exit(1);
    });
}

export { characterMovesData, seedCharacterMoves };
