import 'dotenv/config';
import { CharacterMoveModel } from '../models/CharacterMove';
import { createClient, Client } from '@libsql/client';

// キャラクター技データのシード
// ソースのフレーム表に基づく全キャラクターの技データ

const characterMovesData = {
  'ソル=バッドガイ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6S', moveNotation: '6S' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ガンフレイム', moveNotation: 'ガンフレイム' },
    { moveName: 'ヴォルカニックヴァイパー', moveNotation: 'ヴォルカニックヴァイパー' },
    { moveName: 'バンディットリヴォルバー', moveNotation: 'バンディットリヴォルバー' },
    { moveName: 'バンディットブリンガー', moveNotation: 'バンディットブリンガー' },
    { moveName: 'ぶっきらぼうに投げる', moveNotation: 'ぶっきらぼうに投げる' },
    { moveName: 'ナイトレイドヴォルテックス', moveNotation: 'ナイトレイドヴォルテックス' },
    { moveName: 'ファフニール', moveNotation: 'ファフニール' },
    { moveName: 'タイランレイヴ', moveNotation: 'タイランレイヴ' },
    { moveName: 'ヘヴィモブセメタリー', moveNotation: 'ヘヴィモブセメタリー' }
  ],
  'カイ=キスク': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'スタンエッジ', moveNotation: 'スタンエッジ' },
    { moveName: 'チャージスタンエッジ', moveNotation: 'チャージスタンエッジ' },
    { moveName: 'ヴェイパースラスト', moveNotation: 'ヴェイパースラスト' },
    { moveName: 'スタンディッパー', moveNotation: 'スタンディッパー' },
    { moveName: 'フードゥルアルク', moveNotation: 'フードゥルアルク' },
    { moveName: 'ダイアエクラ', moveNotation: 'ダイアエクラ' },
    { moveName: 'ライド・ザ・ライトニング', moveNotation: 'ライド・ザ・ライトニング' },
    { moveName: 'セイクリッドエッジ', moveNotation: 'セイクリッドエッジ' },
    { moveName: 'ドラゴンインストール', moveNotation: 'ドラゴンインストール' }
  ],
  'メイ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '3K', moveNotation: '3K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'イルカさん・横', moveNotation: 'イルカさん・横' },
    { moveName: 'イルカさん・縦', moveNotation: 'イルカさん・縦' },
    { moveName: 'オーバーヘッドキッス', moveNotation: 'オーバーヘッドキッス' },
    { moveName: '有栖川スパークル', moveNotation: '有栖川スパークル' },
    { moveName: 'グレート山田アタック', moveNotation: 'グレート山田アタック' },
    { moveName: '五所川原', moveNotation: '五所川原' }
  ],
  'アクセル・ロウ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '鎌閃撃', moveNotation: '鎌閃撃' },
    { moveName: '曲鎖撃', moveNotation: '曲鎖撃' },
    { moveName: '旋鎖撃', moveNotation: '旋鎖撃' },
    { moveName: '鬼灯', moveNotation: '鬼灯' },
    { moveName: '冬蟷螂', moveNotation: '冬蟷螂' },
    { moveName: '潦', moveNotation: '潦' },
    { moveName: '蝸牛', moveNotation: '蝸牛' },
    { moveName: '虎落笛', moveNotation: '虎落笛' },
    { moveName: 'アクセルボンバー', moveNotation: 'アクセルボンバー' },
    { moveName: '百重鎌焼', moveNotation: '百重鎌焼' },
    { moveName: 'ワンヴィジョン', moveNotation: 'ワンヴィジョン' }
  ],
  'チップ・ザナフ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'αブレード', moveNotation: 'αブレード' },
    { moveName: 'βブレード', moveNotation: 'βブレード' },
    { moveName: 'γブレード', moveNotation: 'γブレード' },
    { moveName: '冽掌', moveNotation: '冽掌' },
    { moveName: '麓砕', moveNotation: '麓砕' },
    { moveName: '穿踵', moveNotation: '穿踵' },
    { moveName: '幻朧斬', moveNotation: '幻朧斬' },
    { moveName: '手裏剣', moveNotation: '手裏剣' },
    { moveName: '綱張り', moveNotation: '綱張り' },
    { moveName: '万鬼滅砕', moveNotation: '万鬼滅砕' },
    { moveName: '斬星狼牙', moveNotation: '斬星狼牙' }
  ],
  'ポチョムキン': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ハンマフォール', moveNotation: 'ハンマフォール' },
    { moveName: 'ハンマフォールブレーキ', moveNotation: 'ハンマフォールブレーキ' },
    { moveName: 'ポチョムキンバスター', moveNotation: 'ポチョムキンバスター' },
    { moveName: 'ヒートナックル', moveNotation: 'ヒートナックル' },
    { moveName: 'メガフィスト', moveNotation: 'メガフィスト' },
    { moveName: 'スライドヘッド', moveNotation: 'スライドヘッド' },
    { moveName: 'F.D.B.', moveNotation: 'F.D.B.' },
    { moveName: 'ガルダインパクト', moveNotation: 'ガルダインパクト' },
    { moveName: 'ヒートタックル', moveNotation: 'ヒートタックル' },
    { moveName: 'ヘブンリーポチョムキンバスター', moveNotation: 'ヘブンリーポチョムキンバスター' },
    { moveName: 'ガイガンター改', moveNotation: 'ガイガンター改' }
  ],
  'ファウスト': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '突きます', moveNotation: '突きます' },
    { moveName: '引き戻し', moveNotation: '引き戻し' },
    { moveName: 'ナイスショット', moveNotation: 'ナイスショット' },
    { moveName: '何が出るかな？', moveNotation: '何が出るかな？' },
    { moveName: '涅和混練', moveNotation: '涅和混練' },
    { moveName: 'メッタ刈り', moveNotation: 'メッタ刈り' },
    { moveName: '愛', moveNotation: '愛' },
    { moveName: '久延毘古', moveNotation: '久延毘古' },
    { moveName: 'エキサイティング骨折', moveNotation: 'エキサイティング骨折' },
    { moveName: 'な・な・な・なにがでるかな？', moveNotation: 'な・な・な・なにがでるかな？' }
  ],
  'ミリア・レイジ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'タンデムトップ', moveNotation: 'タンデムトップ' },
    { moveName: 'ラストシェイカー', moveNotation: 'ラストシェイカー' },
    { moveName: 'アイアンセイバー', moveNotation: 'アイアンセイバー' },
    { moveName: 'バッドムーン', moveNotation: 'バッドムーン' },
    { moveName: '高速落下', moveNotation: '高速落下' },
    { moveName: 'ミラーシュ', moveNotation: 'ミラーシュ' },
    { moveName: 'カピエル', moveNotation: 'カピエル' },
    { moveName: 'セプテムヴォイシズ', moveNotation: 'セプテムヴォイシズ' },
    { moveName: 'ウィンガー', moveNotation: 'ウィンガー' }
  ],
  'ザトー=ONE': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'インヴァイトヘル', moveNotation: 'インヴァイトヘル' },
    { moveName: '「突く」', moveNotation: '「突く」' },
    { moveName: '「多い！」', moveNotation: '「多い！」' },
    { moveName: '「跳ねる」', moveNotation: '「跳ねる」' },
    { moveName: '「張り合う」', moveNotation: '「張り合う」' },
    { moveName: 'ダムドファング', moveNotation: 'ダムドファング' },
    { moveName: 'ブレイク・ザ・ロウ', moveNotation: 'ブレイク・ザ・ロウ' },
    { moveName: 'ドランカーシェイド', moveNotation: 'ドランカーシェイド' },
    { moveName: 'エディ召喚', moveNotation: 'エディ召喚' },
    { moveName: '収納', moveNotation: '収納' },
    { moveName: 'アモルファス', moveNotation: 'アモルファス' },
    { moveName: 'サンヴォイド', moveNotation: 'サンヴォイド' }
  ],
  'ラムレザル=ヴァレンタイン': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'バヨネート', moveNotation: 'バヨネート' },
    { moveName: 'ダウロ', moveNotation: 'ダウロ' },
    { moveName: 'シルドデトルオ', moveNotation: 'シルドデトルオ' },
    { moveName: 'サブロバート', moveNotation: 'サブロバート' },
    { moveName: 'エラルルーモ', moveNotation: 'エラルルーモ' },
    { moveName: 'オンド', moveNotation: 'オンド' },
    { moveName: 'アグレーサオルドーノ', moveNotation: 'アグレーサオルドーノ' },
    { moveName: 'カルヴァドス', moveNotation: 'カルヴァドス' },
    { moveName: 'モルトバート', moveNotation: 'モルトバート' }
  ],
  'レオ・ホワイトファング': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'グラヴィエットヴァーダ', moveNotation: 'グラヴィエットヴァーダ' },
    { moveName: 'アイゼンシュトルム', moveNotation: 'アイゼンシュトルム' },
    { moveName: 'エアースト・カルタスゲシュトゥーバー', moveNotation: 'エアースト・カルタスゲシュトゥーバー' },
    { moveName: 'ツヴァイト・カルタスゲシュトゥーバー', moveNotation: 'ツヴァイト・カルタスゲシュトゥーバー' },
    { moveName: 'トゥルブレンツ', moveNotation: 'トゥルブレンツ' },
    { moveName: 'グレンツェンドゥンケル', moveNotation: 'グレンツェンドゥンケル' },
    { moveName: 'ブリッツシュラーク', moveNotation: 'ブリッツシュラーク' },
    { moveName: 'シュタイルヴァービル', moveNotation: 'シュタイルヴァービル' },
    { moveName: 'ライデンシャフトディリガント', moveNotation: 'ライデンシャフトディリガント' },
    { moveName: 'カーンシルト', moveNotation: 'カーンシルト' }
  ],
  'ナゴリユキ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '粒雪', moveNotation: '粒雪' },
    { moveName: '不香', moveNotation: '不香' },
    { moveName: '冠雪', moveNotation: '冠雪' },
    { moveName: '垂雪', moveNotation: '垂雪' },
    { moveName: 'Bloodsucking Universe', moveNotation: 'Bloodsucking Universe' },
    { moveName: '忘れ雪', moveNotation: '忘れ雪' },
    { moveName: '残雪', moveNotation: '残雪' }
  ],
  'ジオヴァーナ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'トロヴァォン', moveNotation: 'トロヴァォン' },
    { moveName: 'セパルトゥラ', moveNotation: 'セパルトゥラ' },
    { moveName: 'ソウ・ナセンテ', moveNotation: 'ソウ・ナセンテ' },
    { moveName: 'ソウ・ポエンチ', moveNotation: 'ソウ・ポエンチ' },
    { moveName: 'ヴェンターニア', moveNotation: 'ヴェンターニア' },
    { moveName: 'テンペスターヂ', moveNotation: 'テンペスターヂ' }
  ],
  'アンジー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '疾', moveNotation: '疾' },
    { moveName: '水月のハコビ', moveNotation: '水月のハコビ' },
    { moveName: '紅', moveNotation: '紅' },
    { moveName: '風神', moveNotation: '風神' },
    { moveName: '針・壱式', moveNotation: '針・壱式' },
    { moveName: '一足飛び', moveNotation: '一足飛び' },
    { moveName: '凪刃', moveNotation: '凪刃' },
    { moveName: '臨', moveNotation: '臨' },
    { moveName: '一誠奥義「彩」', moveNotation: '一誠奥義「彩」' },
    { moveName: '花鳥風月・改', moveNotation: '花鳥風月・改' }
  ],
  'イノ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '大木をさする手', moveNotation: '大木をさする手' },
    { moveName: '狂言実行', moveNotation: '狂言実行' },
    { moveName: '抗鬱音階', moveNotation: '抗鬱音階' },
    { moveName: 'ケミカル愛情', moveNotation: 'ケミカル愛情' },
    { moveName: '狂愛アジタート', moveNotation: '狂愛アジタート' },
    { moveName: 'メガロマニア', moveNotation: 'メガロマニア' },
    { moveName: '限界フォルテッシモ', moveNotation: '限界フォルテッシモ' }
  ],
  'ゴールドルイス': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ベヒモスタイフーン', moveNotation: 'ベヒモスタイフーン' },
    { moveName: 'サンダーバード', moveNotation: 'サンダーバード' },
    { moveName: 'スカイフィッシュ', moveNotation: 'スカイフィッシュ' },
    { moveName: 'ダウン・ウィズ・ザ・システム', moveNotation: 'ダウン・ウィズ・ザ・システム' },
    { moveName: 'バーン・イット・ダウン', moveNotation: 'バーン・イット・ダウン' }
  ],
  'ジャック・オー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'サーヴァント召喚', moveNotation: 'サーヴァント召喚' },
    { moveName: 'サーヴァントを投げる', moveNotation: 'サーヴァントを投げる' },
    { moveName: '回収', moveNotation: '回収' },
    { moveName: '攻撃指示', moveNotation: '攻撃指示' },
    { moveName: '防御指示', moveNotation: '防御指示' },
    { moveName: 'カウントダウン', moveNotation: 'カウントダウン' },
    { moveName: 'サーヴァントシュート', moveNotation: 'サーヴァントシュート' },
    { moveName: 'フォーエヴァーエリシオンドライバー', moveNotation: 'フォーエヴァーエリシオンドライバー' },
    { moveName: 'サーヴァントを激励する', moveNotation: 'サーヴァントを激励する' }
  ],
  'ハッピーカオス': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6S', moveNotation: '6S' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '銃を構える', moveNotation: '銃を構える' },
    { moveName: '射撃', moveNotation: '射撃' },
    { moveName: 'しっかり狙う', moveNotation: 'しっかり狙う' },
    { moveName: 'リロード', moveNotation: 'リロード' },
    { moveName: 'フォーカス', moveNotation: 'フォーカス' },
    { moveName: '前転', moveNotation: '前転' },
    { moveName: 'スケープゴート', moveNotation: 'スケープゴート' },
    { moveName: 'カース', moveNotation: 'カース' },
    { moveName: 'デウス・エクス・マキナ', moveNotation: 'デウス・エクス・マキナ' },
    { moveName: '超フォーカス', moveNotation: '超フォーカス' }
  ],
  'バイケン': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '畳返し', moveNotation: '畳返し' },
    { moveName: '蚊鉤', moveNotation: '蚊鉤' },
    { moveName: '妖斬扇', moveNotation: '妖斬扇' },
    { moveName: '柊', moveNotation: '柊' },
    { moveName: '連ね三途渡し', moveNotation: '連ね三途渡し' },
    { moveName: '拳銃', moveNotation: '拳銃' }
  ],
  'テスタメント': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'グレイブリーパー', moveNotation: 'グレイブリーパー' },
    { moveName: 'アンホーリーダイバー', moveNotation: 'アンホーリーダイバー' },
    { moveName: 'ポゼッション', moveNotation: 'ポゼッション' },
    { moveName: 'アービターサイン', moveNotation: 'アービターサイン' },
    { moveName: 'ノストロヴィア', moveNotation: 'ノストロヴィア' },
    { moveName: 'カラミティ・ワン', moveNotation: 'カラミティ・ワン' }
  ],
  'ブリジット': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ストップ&ダッシュ', moveNotation: 'ストップ&ダッシュ' },
    { moveName: 'ローリング移動', moveNotation: 'ローリング移動' },
    { moveName: 'スターシップ', moveNotation: 'スターシップ' },
    { moveName: 'キックスタートマイハート', moveNotation: 'キックスタートマイハート' },
    { moveName: 'ロジャーダイブ', moveNotation: 'ロジャーダイブ' },
    { moveName: 'ロック ザ ベイビー', moveNotation: 'ロック ザ ベイビー' },
    { moveName: 'ループ ザ ループ', moveNotation: 'ループ ザ ループ' },
    { moveName: '帰ってきたキルマシーン', moveNotation: '帰ってきたキルマシーン' }
  ],
  'シン・キスク': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ビークドライバー', moveNotation: 'ビークドライバー' },
    { moveName: 'ホークベイカー', moveNotation: 'ホークベイカー' },
    { moveName: 'フーフスタンプ', moveNotation: 'フーフスタンプ' },
    { moveName: 'エルクハント', moveNotation: 'エルクハント' },
    { moveName: 'ガゼルステップ', moveNotation: 'ガゼルステップ' },
    { moveName: '育ち盛りだからな。', moveNotation: '育ち盛りだからな。' },
    { moveName: 'R.T.L', moveNotation: 'R.T.L' },
    { moveName: 'タイランバレル', moveNotation: 'タイランバレル' }
  ],
  'ベッドマン?': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '4BA', moveNotation: '4BA' },
    { moveName: '4B3', moveNotation: '4B3' },
    { moveName: '4B9', moveNotation: '4B9' },
    { moveName: '0x$0.20', moveNotation: '0x$0.20' },
    { moveName: '0x$1.00', moveNotation: '0x$1.00' },
    { moveName: '13C', moveNotation: '13C' },
    { moveName: '4CC', moveNotation: '4CC' }
  ],
  'アスカR#': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '詠唱', moveNotation: '詠唱' },
    { moveName: 'ブックマーク', moveNotation: 'ブックマーク' },
    { moveName: 'マナ回復', moveNotation: 'マナ回復' },
    { moveName: 'テストケース変更', moveNotation: 'テストケース変更' },
    { moveName: 'サブミクロン粒子高圧縮球', moveNotation: 'サブミクロン粒子高圧縮球' },
    { moveName: 'ハウリングメトロン', moveNotation: 'ハウリングメトロン' },
    { moveName: 'メトロンスクリーマー808', moveNotation: 'メトロンスクリーマー808' },
    { moveName: 'メトロンアルペジオ', moveNotation: 'メトロンアルペジオ' },
    { moveName: 'タルドゥスメトロンディレイ', moveNotation: 'タルドゥスメトロンディレイ' },
    { moveName: 'テラメトロン', moveNotation: 'テラメトロン' },
    { moveName: 'アキピテルメトロン', moveNotation: 'アキピテルメトロン' },
    { moveName: 'アクィラメトロン', moveNotation: 'アクィラメトロン' },
    { moveName: 'ビットシフトメトロン', moveNotation: 'ビットシフトメトロン' },
    { moveName: 'RMSブーストメトロン', moveNotation: 'RMSブーストメトロン' },
    { moveName: 'ゴートゥマーカー', moveNotation: 'ゴートゥマーカー' }
  ],
  'ジョニー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ミストファイナー', moveNotation: 'ミストファイナー' },
    { moveName: 'ターンアップ', moveNotation: 'ターンアップ' },
    { moveName: 'ディール', moveNotation: 'ディール' },
    { moveName: '跳躍', moveNotation: '跳躍' },
    { moveName: '燕穿牙', moveNotation: '燕穿牙' },
    { moveName: 'それが俺の名だ', moveNotation: 'それが俺の名だ' },
    { moveName: 'ジョーカートリック', moveNotation: 'ジョーカートリック' }
  ],
  'エルフェルト': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'Missシャルロット', moveNotation: 'Missシャルロット' },
    { moveName: 'ボンボン・ショコラ', moveNotation: 'ボンボン・ショコラ' },
    { moveName: 'やります！', moveNotation: 'やります！' },
    { moveName: '決めます！', moveNotation: '決めます！' },
    { moveName: 'ジュガント ダ パルフェーオ', moveNotation: 'ジュガント ダ パルフェーオ' },
    { moveName: 'ボンボニエール', moveNotation: 'ボンボニエール' }
  ],
  'A.B.A': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '結合と変性', moveNotation: '結合と変性' },
    { moveName: '変転と感化', moveNotation: '変転と感化' },
    { moveName: '牽引と髄順', moveNotation: '牽引と髄順' },
    { moveName: '戮力と傾動', moveNotation: '戮力と傾動' },
    { moveName: '威喝と嗚咽', moveNotation: '威喝と嗚咽' },
    { moveName: '抑圧と束縛', moveNotation: '抑圧と束縛' },
    { moveName: '逆上と驚愕', moveNotation: '逆上と驚愕' },
    { moveName: '断罪と情動', moveNotation: '断罪と情動' },
    { moveName: '鍵の支配者', moveNotation: '鍵の支配者' },
    { moveName: '鍵の守護者', moveNotation: '鍵の守護者' }
  ],
  'スレイヤー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'マッパハンチ', moveNotation: 'マッパハンチ' },
    { moveName: 'ダンディーステップ', moveNotation: 'ダンディーステップ' },
    { moveName: 'パイルバンカー', moveNotation: 'パイルバンカー' },
    { moveName: 'バンプアヘッド', moveNotation: 'バンプアヘッド' },
    { moveName: 'イッツレイト', moveNotation: 'イッツレイト' },
    { moveName: 'マスターズハンマー', moveNotation: 'マスターズハンマー' },
    { moveName: '血を吸う宇宙', moveNotation: '血を吸う宇宙' },
    { moveName: 'ハンドオブドゥーム', moveNotation: 'ハンドオブドゥーム' },
    { moveName: 'スーパーマッパハンチ', moveNotation: 'スーパーマッパハンチ' },
    { moveName: 'ラスト・ホライズン', moveNotation: 'ラスト・ホライズン' }
  ],
  'ディズィー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: '魚を捕る時に使ってたんです', moveNotation: '魚を捕る時に使ってたんです' },
    { moveName: '氷原', moveNotation: '氷原' },
    { moveName: '焼き栗が欲しい時に使ってたんです', moveNotation: '焼き栗が欲しい時に使ってたんです' },
    { moveName: 'よく話し相手になってくれました', moveNotation: 'よく話し相手になってくれました' },
    { moveName: 'ミカエルソード', moveNotation: 'ミカエルソード' },
    { moveName: '光の翼', moveNotation: '光の翼' },
    { moveName: 'インペリアルレイ', moveNotation: 'インペリアルレイ' },
    { moveName: 'ガンマレイ', moveNotation: 'ガンマレイ' }
  ],
  'ヴェノム': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6K', moveNotation: '6K' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ボール', moveNotation: 'ボール' },
    { moveName: 'ボール生成', moveNotation: 'ボール生成' },
    { moveName: 'ＱＶ', moveNotation: 'ＱＶ' },
    { moveName: 'スティンガー', moveNotation: 'スティンガー' },
    { moveName: 'カーカス', moveNotation: 'カーカス' },
    { moveName: 'トリアンバカ', moveNotation: 'トリアンバカ' },
    { moveName: 'ダークエンジェル', moveNotation: 'ダークエンジェル' },
    { moveName: 'ナヴァラートナ', moveNotation: 'ナヴァラートナ' }
  ],
  'ユニカ': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'ストリーク', moveNotation: 'ストリーク' },
    { moveName: 'ペネ', moveNotation: 'ペネ' },
    { moveName: 'トップ', moveNotation: 'トップ' },
    { moveName: 'ブラスト', moveNotation: 'ブラスト' },
    { moveName: 'ブレイズ', moveNotation: 'ブレイズ' },
    { moveName: 'ブリッツ', moveNotation: 'ブリッツ' },
    { moveName: 'メガデス', moveNotation: 'メガデス' },
    { moveName: 'ウェポンズフリー', moveNotation: 'ウェポンズフリー' }
  ],
  'ルーシー': [
    { moveName: '5P', moveNotation: '5P' },
    { moveName: '5K', moveNotation: '5K' },
    { moveName: '近S', moveNotation: '近S' },
    { moveName: '遠S', moveNotation: '遠S' },
    { moveName: '5H', moveNotation: '5H' },
    { moveName: '2P', moveNotation: '2P' },
    { moveName: '2K', moveNotation: '2K' },
    { moveName: '2S', moveNotation: '2S' },
    { moveName: '2H', moveNotation: '2H' },
    { moveName: '6P', moveNotation: '6P' },
    { moveName: '6H', moveNotation: '6H' },
    { moveName: '2D', moveNotation: '2D' },
    { moveName: '5D', moveNotation: '5D' },
    { moveName: 'モノワイヤー', moveNotation: 'モノワイヤー' },
    { moveName: 'ユニティ', moveNotation: 'ユニティ' },
    { moveName: 'スプリントアタック', moveNotation: 'スプリントアタック' },
    { moveName: 'モノワイヤー・ブレイクアウト', moveNotation: 'モノワイヤー・ブレイクアウト' },
    { moveName: 'ライブワイヤー', moveNotation: 'ライブワイヤー' },
    { moveName: 'クイックハック', moveNotation: 'クイックハック' }
  ]
};

export async function seedCharacterMoves() {
  console.log('Seeding character moves...');

  let totalCreated = 0;

  for (const [characterName, moves] of Object.entries(characterMovesData)) {
    console.log(`  Seeding moves for ${characterName}...`);

    try {
      await CharacterMoveModel.bulkCreate(characterName, moves);
      totalCreated += moves.length;
      console.log(`    ✓ Created ${moves.length} moves`);
    } catch (error) {
      console.error(`    ✗ Error seeding ${characterName}:`, error);
    }
  }

  console.log(`✓ Total moves created: ${totalCreated}`);
}

// スクリプトとして直接実行された場合
if (require.main === module) {
  const url = process.env.TURSO_DATABASE_URL;
  const authToken = process.env.TURSO_AUTH_TOKEN;

  if (!url || !authToken) {
    console.error('TURSO_DATABASE_URL and TURSO_AUTH_TOKEN must be set');
    process.exit(1);
  }

  // データベース接続を作成
  const db: Client = createClient({ url, authToken });
  console.log('Connected to database');

  // database/index.ts のdbをセット
  const { setDatabase } = require('./index.ts');
  setDatabase(db);

  seedCharacterMoves()
    .then(() => {
      console.log('Seed completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seed failed:', error);
      process.exit(1);
    });
}
